services:
  app:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/database/data
      - logs_volume:/app/logs
    user: "1000:1000"
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local
  logs_volume:
    driver: local